from tools.gastos import (
    registrar_gasto,
    listar_gastos,
    editar_gasto,
    eliminar_gasto,
    consultar_total,
)
from tools.fijos import (
    registrar_gasto_fijo,
    listar_gastos_fijos,
    editar_gasto_fijo,
    eliminar_gasto_fijo,
    registrar_ingreso_fijo,
    listar_ingresos_fijos,
    editar_ingreso_fijo,
    eliminar_ingreso_fijo,
)
from tools.despensa import (
    agregar_producto_despensa,
    listar_productos_despensa,
    editar_producto_despensa,
    quitar_producto_despensa,
    registrar_compra_despensa,
    listar_compras_despensa,
    editar_compra_despensa,
    eliminar_compra_despensa,
    generar_lista_despensa,
    consultar_prediccion_despensa,
)
from tools.presupuestos import (
    crear_presupuesto,
    ver_presupuestos,
    editar_presupuesto,
    eliminar_presupuesto,
)
from tools.tickets import (
    procesar_ticket,
    listar_tickets,
    eliminar_ticket,
)

ALL_TOOLS = [
    registrar_gasto,
    listar_gastos,
    editar_gasto,
    eliminar_gasto,
    consultar_total,
    registrar_gasto_fijo,
    listar_gastos_fijos,
    editar_gasto_fijo,
    eliminar_gasto_fijo,
    registrar_ingreso_fijo,
    listar_ingresos_fijos,
    editar_ingreso_fijo,
    eliminar_ingreso_fijo,
    agregar_producto_despensa,
    listar_productos_despensa,
    editar_producto_despensa,
    quitar_producto_despensa,
    registrar_compra_despensa,
    listar_compras_despensa,
    editar_compra_despensa,
    eliminar_compra_despensa,
    generar_lista_despensa,
    consultar_prediccion_despensa,
    crear_presupuesto,
    ver_presupuestos,
    editar_presupuesto,
    eliminar_presupuesto,
    procesar_ticket,
    listar_tickets,
    eliminar_ticket,
]
